{{- if .Values.certs.web.create }}
{{ $fullname := include "dex.fullname" . }}
{{ $tlsBuiltName := printf "%s-tls" $fullname }}
{{ $tlsSecretName := default $tlsBuiltName .Values.certs.web.secret.tlsName }}
{{ $caBuiltName := printf "%s-ca" $fullname }}
{{ $caName := default $caBuiltName .Values.certs.web.secret.caName }}

{{ $caDays := int .Values.certs.web.caDays }}
{{ $ca := genCA "dex-ca" $caDays }}
{{ $cn := printf "%s-%s.%s.svc" .Release.Name .Chart.Name .Release.Namespace }}
{{ $certDays := int .Values.certs.web.certDays }}
{{ $server := genSignedCert $cn nil nil $certDays $ca }}

apiVersion: v1
kind: List
metadata:
items:

- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: {{ template "dex.name" . }}
      chart: {{ template "dex.chart" . }}
      heritage: "{{ .Release.Service }}"
      release: "{{ .Release.Name }}"
    name: {{ $caName | quote }}
  data:
    dex-ca.pem: {{ b64enc $ca.Cert }}

- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: {{ template "dex.name" . }}
      chart: {{ template "dex.chart" . }}
      heritage: "{{ .Release.Service }}"
      release: "{{ .Release.Name }}"
    name: {{ $tlsSecretName }}
  data:
    tls.crt: {{ b64enc $server.Cert }}
    tls.key: {{ b64enc $server.Key }}
  
- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: {{ template "dex.name" . }}
      chart: {{ template "dex.chart" . }}
      heritage: "{{ .Release.Service }}"
      release: "{{ .Release.Name }}"
    name: {{ $caName | quote }}
  data:
    tls.crt: {{ b64enc $ca.Cert }}
    tls.key: {{ b64enc $ca.Key }}

- apiVersion: v1
  kind: Secret
  metadata:
    labels:
      app: {{ template "dex.name" . }}
      chart: {{ template "dex.chart" . }}
      heritage: "{{ .Release.Service }}"
      release: "{{ .Release.Name }}"
    name: {{ template "dex.fullname" . }}
  data:
    config.yaml: {{ toYaml .Values.config | b64enc }}

{{- end }}
